name: weather-bot
on:
  workflow_dispatch:
  schedule:
    - cron: "00 20 * * *" # Everyday AM 5:00 KST

jobs:
  post_weather_forecast_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 라이브러리 파일이 저장된 node_modules 폴더 캐시
      - name: Cache dependencies
        id: node-cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 캐시가 있으면 라이브러리를 설치하지 않음
      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Run script
        env:
          OPEN_DATA_SERVICE_KEY: ${{ secrets.OPEN_DATA_SERVICE_KEY }}
          OWNER: ${{ secrets.OWNER }}
          REPO: ${{ secrets.REPO }}
          TOKEN: ${{ secrets.TOKEN }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        run: node src/main.js
